### ISSUE TITLE
Golang version example

### ISSUE THREAD

**Issue by unlikezy** [jtattermusch/grpc-loadbalancing-kubernetes-examples#1]
Hi, @jtattermusch , the examples you presented is great. 
But the interfaces and the implement between different program language are so different that I still find it difficult for me to fullfil some specific loadbalancing in golang.
Could you provide some golang version of these example? Thanks.

**Comment by jtattermusch** [comment]
Hi sorry, I have no plans providing examples in go (but the principles should be the same - is there anything particular you're struggling with? What example are you having trouble with?). Btw, there should be plenty of go LB examples available online.
